"""
Low-level PDF helpers shared across the app (report generation, admin exports).
Disease-specific report layout lives in app/modules/reports/pdf_generator.py; this module
only provides generic building blocks (styles, chart embedding, header/footer).
"""
from __future__ import annotations
import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Table, TableStyle, HRFlowable,
)

BRAND_COLOR = colors.HexColor("#0F766E")     # teal - matches a typical healthcare palette
RISK_COLORS = {
    "Low Risk": colors.HexColor("#16A34A"),
    "Moderate Risk": colors.HexColor("#CA8A04"),
    "High Risk": colors.HexColor("#EA580C"),
    "Critical Risk": colors.HexColor("#DC2626"),
}


def get_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="BrandTitle", fontSize=20, textColor=BRAND_COLOR, spaceAfter=6, leading=24))
    styles.add(ParagraphStyle(name="SectionHeading", fontSize=13, textColor=BRAND_COLOR,
                               spaceBefore=14, spaceAfter=6, leading=16))
    styles.add(ParagraphStyle(name="Body", fontSize=10, leading=14))
    styles.add(ParagraphStyle(name="Small", fontSize=8, textColor=colors.grey, leading=10))
    return styles


def new_document(buffer: io.BytesIO) -> SimpleDocTemplate:
    return SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=18 * mm, bottomMargin=18 * mm, leftMargin=18 * mm, rightMargin=18 * mm,
    )


def divider() -> HRFlowable:
    return HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E5E7EB"), spaceBefore=4, spaceAfter=10)


def risk_badge_table(risk_level: str, probability: float, confidence: float):
    styles = get_styles()
    color = RISK_COLORS.get(risk_level, colors.grey)
    data = [[
        Paragraph(f"<b>{risk_level}</b>", ParagraphStyle(name="badge", fontSize=14, textColor=colors.white)),
        Paragraph(f"Risk Probability<br/><b>{probability * 100:.1f}%</b>", styles["Body"]),
        Paragraph(f"Model Confidence<br/><b>{confidence * 100:.1f}%</b>", styles["Body"]),
    ]]
    table = Table(data, colWidths=[150, 170, 170])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, 0), color),
        ("BACKGROUND", (1, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 0), (0, 0), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
    ]))
    return table


def footer_text() -> str:
    return (f"Generated by AI Precision Healthcare Platform on "
            f"{datetime.utcnow().strftime('%d %b %Y, %H:%M UTC')}. This report is an AI-generated "
            f"preliminary risk assessment and does NOT constitute a medical diagnosis. Always consult "
            f"a licensed physician before making any healthcare decisions.")
